apiVersion: v1
kind: Secret
metadata:
  name: ocp-terraform-secret-CLUSTERID
type: Opaque
data:
  ibm-api-key: '<IBMCLOUD_API_KEY>'
  rh_username: '<RHEL_SUBS_USERNAME>'
  rh_password: '<RHEL_SUBS_PASSWORD>'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ocp-terraform-config-CLUSTERID
data:
  secrets: |
    <PULL_SECRET>
